### ISSUE TITLE
Control the generation of enemies?

### ISSUE THREAD

**Issue by Thecobrax052** [VeroxUniverse/EpicSamurai-forge#3]
Control the generation of enemies?

Any way to control the way the enemies spawn? since the fox spawns in the village and kills all my villagers

**Comment by VeroxUniverse** [comment]
I can remove villagers from his goals.

**Comment by Thecobrax052** [comment]
Hello, I'm still delighted with this mod, since I use it with come alive, however I keep putting the game in pasifico since there are enemies that spawn in the world and attack the villagers, right now the little ghost burns the villagers, anyway I return to my question, the aforementioned option that the enemies do not attack the villagers would be a very good option, or, like other mods, a file can be found in the config folder, to deactivate the mobs, or just the mods that are generated in the normal world do not attack the villagers

**Comment by VeroxUniverse** [comment]
I am working on it but I am very busy at the moment because of my exams. And I am working on 3 projects at the same time so its not that easy to work on every project at the same time. Since I am porting Epic Paladins now.
